# fly.toml app configuration file generated for three-minutes-ws on 2026-04-11T19:58:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'three-minutes-ws'
primary_region = 'fra'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/socket.io/?EIO=4&transport=polling'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
